name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git clone https://viki77:${HF_TOKEN}@huggingface.co/spaces/viki77/AI-Powered_Recruitment_Agent space_repo
          rsync -av --exclude='.git' . space_repo/
          cd space_repo
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          git push https://viki77:${HF_TOKEN}@huggingface.co/spaces/viki77/AI-Powered_Recruitment_Agent.git HEAD:main
